# Generated by Django 5.2.6 on 2025-10-10 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diasemana_eventoespecial_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor (Assinatura)')),
                ('imagem', models.ImageField(upload_to='devocionais/', verbose_name='Imagem Ilustrativa')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Devocional',
                'verbose_name_plural': 'Devocionais',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.AlterField(
            model_name='diasemana',
            name='icone',
            field=models.CharField(max_length=50, verbose_name='Ícone'),
        ),
    ]
