# Generated by Django 5.2.7 on 2025-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_devocional_alter_diasemana_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Pessoa')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='memorial/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição (menor número aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Pessoa do Memorial',
                'verbose_name_plural': 'Pessoas do Memorial',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pastor')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período no Pastorado')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, verbose_name='Descrição Curta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pastores/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição (menor número aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Pastor (Histórico)',
                'verbose_name_plural': 'Pastores (Histórico)',
                'ordering': ['ordem'],
            },
        ),
        migrations.RemoveField(
            model_name='diasemana',
            name='icone',
        ),
    ]
